name: Cassandra

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install libuv1-dev
          sudo snap install valgrind --classic
          pip3 install https://github.com/scylladb/scylla-ccm/archive/master.zip
          sudo sh -c "echo 2097152 >> /proc/sys/fs/aio-max-nr"

      - name: Build
        run: cmake -DCASS_BUILD_INTEGRATION_TESTS=ON . && make

      - name: Run integration tests on Cassandra 4.0.7
        env:
          #        Ignored tests are added in the end, after the "-" sign.
          Tests: "ClusterTests.*\
:BasicsTests.*\
:PreparedTests.*\
:CassandraTypes/CassandraTypesTests/*.Integration_Cassandra_*\
:ErrorTests.*\
:SslClientAuthenticationTests*:SslNoClusterTests*:SslNoSslOnClusterTests*:SslTests*\
:SchemaMetadataTest.*KeyspaceMetadata:SchemaMetadataTest.*MetadataIterator:SchemaMetadataTest.*View*\
:TracingTests.*\
:ByNameTests.*\
:CompressionTests.*\
:LoggingTests.*\
:-PreparedTests.Integration_Cassandra_PreparedIDUnchangedDuringReprepare\
:PreparedTests.Integration_Cassandra_FailFastWhenPreparedIDChangesDuringReprepare\
:*5.Integration_Cassandra_*\
:*19.Integration_Cassandra_*\
:*7.Integration_Cassandra_*\
:SslTests.Integration_Cassandra_ReconnectAfterClusterCrashAndRestart\
:ExecutionProfileTest.InvalidName"
        run: valgrind --error-exitcode=123 --leak-check=full --errors-for-leak-kinds=definite ./cassandra-integration-tests --version=4.0.7 --category=CASSANDRA --verbose=ccm --gtest_filter="$Tests"

      - name: Upload test logs
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-logs-cassandra
          path: ./log/*
