name: Clippy check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Clippy check
      working-directory: ./scylla-rust-wrapper
      run: cargo clippy --verbose -- -D warnings -Aclippy::uninlined_format_args
